FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements/requirements_linux.txt /app/requirements/requirements_linux.txt

RUN pip install --no-cache-dir -r /app/requirements/requirements_linux.txt

COPY . .

ENV PYTHONPATH=/app/src

CMD ["celery", "-A", "src.celery_app", "worker", "-l", "info"]