services:
  store_web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: store_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      store_db:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery_worker
    container_name: store_celery_worker
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery_beat
    container_name: store_celery_beat
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  store_db:
    image: postgres:17-alpine
    container_name: store_db
    ports:
      - "5434:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    restart: always
  
  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"      
      - "15672:15672"    
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT__USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT__PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT__VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 2s
      retries: 2
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data: